
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 4;
  public static final int minus = 10;
  public static final int numberval = 12;
  public static final int textval = 13;
  public static final int semi = 11;
  public static final int EOF = 0;
  public static final int plus = 9;
  public static final int error = 1;
  public static final int rparen = 6;
  public static final int numberdcl = 2;
  public static final int textdcl = 3;
  public static final int lparen = 5;
  public static final int comma = 8;
  public static final int assign = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numberdcl",
  "textdcl",
  "id",
  "lparen",
  "rparen",
  "assign",
  "comma",
  "plus",
  "minus",
  "semi",
  "numberval",
  "textval"
  };
}

